### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by DynamicCode1** [MKAbuMattar/fluentui-emoji#21]
All the emojis have MIT license , so can I use then for my own website ? If yes then what conditions should I satisfy to use these emojis
Can i use them for both personal/commercial use?

**Comment by MKAbuMattar** [comment]
Yes, and for the answer to all questions, check >> [@microsoft/fluentui-emoji/LICENSE](https://github.com/microsoft/fluentui-emoji/blob/main/LICENSE).
