### ISSUE TITLE
50 MB CDN limit

### ISSUE THREAD

**Issue by nuthinking** [MKAbuMattar/fluentui-emoji#26]
Looks like some emojis are not served because the package passed the 50MB size limit:

https://cdn.jsdelivr.net/gh/mkabumattar/fluentui-emoji@latest/icons/modern/NEW-button.svg

<img width="797" alt="Screenshot 2023-08-18 at 08 13 54" src="https://github.com/MKAbuMattar/fluentui-emoji/assets/163635/8744574b-15fd-4eb7-89cf-85695dcfb025">

I can see you already have scripts for optimizing them and indeed the ones served look optimized. How else could be the CDN limit issue fixed?

**Comment by nuthinking** [comment]
In case of "NEW" seems to be a file name issue: https://cdn.jsdelivr.net/gh/mkabumattar/fluentui-emoji@latest/icons/modern/new-button.svg

**Comment by MKAbuMattar** [comment]
As per your suggestion, I've confirmed that the issue is related to file naming. To address this, please refer to the doc at: https://fluentui-emoji.vercel.app/ for guidance on identifying and resolving the naming problems.

**Comment by nuthinking** [comment]
@MKAbuMattar if you don't mind, what would be the ideal way to convert emoji to filename?
